name: Code Quality

on:
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/code-quality.yml"
      - ".golangci.yaml"
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.24"
      - name: Check code quality
        run: make quality
      - name: Format code
        run: make fmt
      - name: Tidy modules
        run: make deps.tidy
      - name: Check no diff
        run: make git.nodiff

  test:
    name: Test
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-arch: [amd64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.24"
      - name: Test coverage and races
        run: make test.race
        env:
          GOARCH: ${{ matrix.go-arch }}
